### ISSUE TITLE
Conversion cuts off initial 25 characters

### ISSUE THREAD

**Issue by neverfox** [jfromaniello/sublime-html-to-jade#1]
With a well-formed index.html that begins:

```
<!DOCTYPE html>
<html lang="en">
```

I get index.html.jade that begins:

```
g='en')
```

Of course, this should be:

```
!!! 5
html(lang='en')
```

And with:

```
<!DOCTYPE html>
<html>
<head>
```

I get:

```
ead
```

In both cases, this is exactly 25 characters, including EOL. This happens with selection conversion also. I'm on Windows running portable Sublime Text 2.0.1, Build 2217 and the 2013-01-17 build of yourr package.

**Comment by jfromaniello** [comment]
Yes! I notice this as well, will fix it asap

2013/2/8, neverfox notifications@github.com:

> With a well-formed index.html that begins:
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> ```
> 
> I get index.html.jade that begins:
> 
> ```
> g='en')
> ```
> 
> Of course, this should be:
> 
> ```
> !!! 5
> html(lang='en')
> ```
> 
> And with:
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
> ```
> 
> I get:
> 
> ```
> ead
> ```
> 
> In both cases, this is exactly 25 characters, including EOL. This happens
> with selection conversion also. I'm on Windows running portable Sublime Text
> 2.0.1, Build 2217 and the 2013-01-17 build of yourr package.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jfromaniello/sublime-html-to-jade/issues/1

## 

Enviado desde mi dispositivo móvil

**Comment by neverfox** [comment]
Thanks! Any progress on this?

**Comment by jfromaniello** [comment]
fixed, sorry for the delay
