### ISSUE TITLE
Error when installing 

### ISSUE THREAD

**Issue by julianpinedayyz** [jfromaniello/sublime-html-to-jade#5]
I get this:

line 1, in <module>
    import urllib2
ImportError: No module named 'urllib2'

I don't know if the previous error is the reason why I can't transform html to jade using Super + P.  Maybe it is?

**Comment by dflourusso** [comment]
I found the same problem.
To solve you need to replace **urllib2** to **urllib.request**.
Sometimes i will create a pull request.

**Comment by julianpinedayyz** [comment]
Can you provide more details?  I think the problem goes back to Sublime-Package-Decontrol.  Can't seem to make that work replacing what you mentioned.

Thanks!

**Comment by dflourusso** [comment]
I am using this one: [OPEN](https://github.com/dflourusso/sublime-html2jade).

It works fine and works offline too.

**Comment by julianpinedayyz** [comment]
Thanks that worked for me.  Now my issue is that it inserts the html and body tag if I convert from a selection or from the clipboard.  Do you know if there's any way to avoid that?

Thanks!

**Comment by dflourusso** [comment]
It uses the plugin [html2jade](https://github.com/donpark/html2jade) to convert.

If you open the file **html2jade.py** at line 50 you can see a call to html2jade.

There you can pass some parameters. In my case i used `--noemptypipe --bodyless --noattrcomma`. You can configure according with your preferences.

**Comment by julianpinedayyz** [comment]
Thanks!  I'm not very savvy with python.  Can you please tell me how to pass the parameters in this code:

```
    html2jade = subprocess.Popen(
        'html2jade',
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        shell=True
    )
```

Thanks!

**Comment by dflourusso** [comment]
In my fork this plugin is working correctly.
See my customization: [OPEN](https://github.com/dflourusso/sublime-html2jade/blob/master/html2jade.py#L50)

**Comment by julianpinedayyz** [comment]
Awesome! Thanks a lot! That really helped me.  Do you know by any chance if there's a way to set the spacing to a tab instead of 2 spaces?  Just wondering ;)

**Comment by dflourusso** [comment]
You can use [THIS](https://github.com/donpark/html2jade#command-line-options) options.

**Comment by julianpinedayyz** [comment]
Ok. You Rock! Thanks a lot!

**Comment by julianpinedayyz** [comment]
I think it would be amazing to create a html2jade.sublime-settings file and have an object with all this options so we don't need to modify the python file.  Something like:

{
  "--double": false,
  "--tabs": true,
  "--donotencode": true,
  "--bodyless": true,
  "--noattrcomma": true,
  "--noemptypipe": true
}

I just don't have enough knowledge to make that happen and it would probably take me weeks to learn python so.... Maybe an improvement for the near future.

Thanks!

**Comment by dflourusso** [comment]
Very good, i do not know about python too, but when i have time i will implement this configuration.
Thanks.
